src/Entity/Contient.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ContientRepository")
 */
class Contient
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Article")
     * @ORM\JoinColumns({
     * @ORM\JoinColumn(name="id_article", referencedColumnName="id_article")
     * })
     */
    private $id_article;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Commande")
     * @ORM\JoinColumns({
     * @ORM\JoinColumn(name="id_commande", referencedColumnName="id_commande")
     * })
     */
    private $id_commande;

    /**
     * @ORM\Column(type="integer")
     */
    private $nombre_article;

    /**
     * @ORM\Column(type="decimal", precision=23, scale=4)
     */
    private $prix_article;

    /**
     * @ORM\Column(type="decimal", precision=23, scale=4)
     */
    private $prix_article_tva;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getIdArticle(): ?Article
    {
        return $this->id_article;
    }

    public function setIdArticle(?Article $id_article): self
    {
        $this->id_article = $id_article;

        return $this;
    }

    public function getIdCommande(): ?Commande
    {
        return $this->id_commande;
    }

    public function setIdCommande(?Commande $id_commande): self
    {
        $this->id_commande = $id_commande;

        return $this;
    }

    public function getNombreArticle(): ?int
    {
        return $this->nombre_article;
    }

    public function setNombreArticle(int $nombre_article): self
    {
        $this->nombre_article = $nombre_article;

        return $this;
    }

    public function getPrixArticle(): ?string
    {
        return $this->prix_article;
    }

    public function setPrixArticle(string $prix_article): self
    {
        $this->prix_article = $prix_article;

        return $this;
    }

    public function getPrixArticleTva(): ?string
    {
        return $this->prix_article_tva;
    }

    public function setPrixArticleTva(string $prix_article_tva): self
    {
        $this->prix_article_tva = $prix_article_tva;

        return $this;
    }
}

src/Entity/Rubrique.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Rubrique
 *
 * @ORM\Table(name="rubrique")
 * @ORM\Entity
 */
class Rubrique
{
    /**
     * @var int
     *
     * @ORM\Column(name="id_rubrique", type="integer", nullable=false)
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="IDENTITY")
     */
    private $idRubrique;

    /**
     * @var string
     *
     * @ORM\Column(name="nom_rubrique", type="string", length=30, nullable=false)
     */
    private $nomRubrique;

    public function getIdRubrique(): ?int
    {
        return $this->idRubrique;
    }

    public function getNomRubrique(): ?string
    {
        return $this->nomRubrique;
    }

    public function setNomRubrique(string $nomRubrique): self
    {
        $this->nomRubrique = $nomRubrique;

        return $this;
    }


}

src/Form/RubriqueType.php
<?php

namespace App\Form;

use App\Entity\Rubrique;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class RubriqueType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('nomRubrique')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Rubrique::class,
        ]);
    }
}

src/Controller/RubriqueController.php
<?php

namespace App\Controller;

use App\Entity\Rubrique;
use App\Entity\SousRubrique;
use App\Entity\Article;
use App\Form\RubriqueType;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/rub")
 */
class RubriqueController extends AbstractController
{
    /**
     * @Route("/", name="rubrique_index", methods={"GET"})
     */
    public function index(): Response
    {

        $articles = $this->getDoctrine()
            ->getRepository(Article::class)
            ->findAll();

        $rubriques = $this->getDoctrine()
            ->getRepository(Rubrique::class)
            ->findAll();

        $sousrubriques = $this->getDoctrine()
            ->getRepository(SousRubrique::class)
            ->findAll();

        return $this->render('rubrique/rubriques.html.twig', [
            'articles' => $articles,
            'rubriques' => $rubriques,
            'sousrubriques' => $sousrubriques,
        ]);
    }

    /**
     * @Route("/new", name="rubrique_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $rubrique = new Rubrique();
        $form = $this->createForm(RubriqueType::class, $rubrique);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($rubrique);
            $entityManager->flush();

            return $this->redirectToRoute('rubrique_index');
        }

        return $this->render('rubrique/new.html.twig', [
            'rubrique' => $rubrique,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{idRubrique}", name="rubrique_show", methods={"GET"})
     */
    public function show(Rubrique $rubrique): Response
    {

        $articles = $this->getDoctrine()
            ->getRepository(Article::class)
            ->findAll();

        $rubriques = $this->getDoctrine()
            ->getRepository(Rubrique::class)
            ->findAll();

        $sousrubriques = $this->getDoctrine()
            ->getRepository(SousRubrique::class)
            ->findAll();


        return $this->render('rubrique/show.html.twig', [
            'articles' => $articles,
            'sousrubriques' => $sousrubriques,
            'rubrique' => $rubrique,
        ]);
    }

    /**
     * @Route("/{idRubrique}/edit", name="rubrique_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Rubrique $rubrique): Response
    {
        $form = $this->createForm(RubriqueType::class, $rubrique);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('rubrique_index');
        }

        return $this->render('rubrique/edit.html.twig', [
            'rubrique' => $rubrique,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{idRubrique}", name="rubrique_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Rubrique $rubrique): Response
    {
        if ($this->isCsrfTokenValid('delete'.$rubrique->getIdRubrique(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($rubrique);
            $entityManager->flush();
        }

        return $this->redirectToRoute('rubrique_index');
    }
}

templates/rubrique/_delete_form.html.twig
<form method="post" action="{{ path('rubrique_delete', {'idRubrique': rubrique.idRubrique}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ rubrique.idRubrique) }}">
    <button class="btn">Delete</button>
</form>

templates/rubrique/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/rubrique/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Rubrique{% endblock %}

{% block body %}
    <h1>Edit Rubrique</h1>

    {{ include('rubrique/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('rubrique_index') }}">back to list</a>

    {{ include('rubrique/_delete_form.html.twig') }}
{% endblock %}

templates/rubrique/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Rubrique index{% endblock %}

{% block body %}
    <h1>Rubrique index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>IdRubrique</th>
                <th>NomRubrique</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for rubrique in rubriques %}
            <tr>
                <td>{{ rubrique.idRubrique }}</td>
                <td>{{ rubrique.nomRubrique }}</td>
                <td>
                    <a href="{{ path('rubrique_show', {'idRubrique': rubrique.idRubrique}) }}">show</a>
                    <a href="{{ path('rubrique_edit', {'idRubrique': rubrique.idRubrique}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="3">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('rubrique_new') }}">Create new</a>
{% endblock %}

templates/rubrique/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Rubrique{% endblock %}

{% block body %}
    <h1>Create new Rubrique</h1>

    {{ include('rubrique/_form.html.twig') }}

    <a href="{{ path('rubrique_index') }}">back to list</a>
{% endblock %}

templates/rubrique/rubriques.html.twig
{% block body %}
	<div class="row">
		<div class="col-12 my-auto">
			<nav class="navbar navbar-expand-lg justify-content-center navbar-light bg-light mt-3 mb-4">
				<ul class="nav navbar-nav flex-row justify-content-center flex-nowrap">
					{% for rubrique in rubriques %}
						<li class="nav-item dropdown">
							<div class="dropdown">
								<a class="btn btn-secondary dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
									{{ rubrique.nomRubrique }}
								</a>
								<div class="dropdown-content">
									{% for sousrubrique in sousrubriques %}
										{% if sousrubrique.idRubrique.idRubrique == rubrique.idRubrique  %}
											<a class='dropdown-item' href="{{ path('sous_rubrique_show', {'idSousRubrique': sousrubrique.idSousRubrique}) }}">{{sousrubrique.nomSousRubrique}}</a>
										{% endif %}
									{% endfor %}
								</div>
							</div>
						</li>
					{% endfor %}
				</ul>
			</nav>
		</div>
	</div>
{% endblock %}

templates/rubrique/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Rubrique{% endblock %}

{% block body %}
  <h1>{{ rubrique.nomRubrique }}</h1>

  <div class="card-deck ">
		<div class="row">
{% for sousRubrique in sousrubriques %}
    {% if sousRubrique.rubrique.idRubrique == sousRubrique.idSousRubrique  %}
       {% for article in articles %}
           {% if sousRubrique.idSousRubrique == article.idSousRubrique.idSousRubrique  %}
                <div class="col-sm-6 col-md-4 col-lg-3 my-4">
						<a href="{{ path('article_show', {'idArticle': article.idArticle}) }}">
							<div class="card " style="height:350px">
								<div class="card-header">
									<img src="{{asset('uploads/images/' ~ article.mainImage)}}" class="card-img-top img-fluid" alt="...">
								</div>
								<div class="card-body text-center text-capitalize">
									<h5 class="card-title">{{article.idFabricant.nomFabricant}}</h5>
									<p class="card-text">
										<h6>Model:
											{{article.modelArticle}}</h6>
										<b>Prix :</b>
										{{article.prixArticle}}<br></p>
								</div>
							</div>
						</a>
					</div>
           {% endif %}
       {% endfor %}
    {% endif %}
{% endfor %}
</div>
</div>

<pre>
    {{ dump(rubrique) }}
</pre>

    <table class="table">
        <tbody>
            <tr>
                <th>IdRubrique</th>
                <td>{{ rubrique.idRubrique }}</td>
            </tr>
            <tr>
                <th>NomRubrique</th>
                <td>{{ rubrique.nomRubrique }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('rubrique_index') }}">back to list</a>

    <a href="{{ path('rubrique_edit', {'idRubrique': rubrique.idRubrique}) }}">edit</a>

    {{ include('rubrique/_delete_form.html.twig') }}
{% endblock %}